# ruby encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Template.destroy_all
Template.create :templateid => "SWOT", :name => "SWOT Analysis", :description => "A structured planning method to evaluate the Strenghts, Weaknesses, Opportunities, and Threats of your project - <a href='http://en.wikipedia.org/wiki/SWOT_analysis'>read more</a>.<br>This option is a good start for everyone using Hyve.me for the first time.", :lang => "en"
Template.create :templateid => "Honeycomb", :name => "Honeycomb Template", :description => "An advancement of the project management triangle in regard to validated learning - <a href='http://www.hyve.me/blog/?p=57'>read more</a>.<br>This is a general purpose template for any kind of project.", :lang => "en"
Template.create :templateid => "Porter", :name => "Porter's 5 Forces", :description => "A framework for industry analysis to evaluate the competitive intensity and attractiveness for a given market - <a href='http://en.wikipedia.org/wiki/Porter%27s_five_forces'>read more</a>.<br>Use this option for business related projects.", :lang => "en"
Template.create :templateid => "Lean", :name => "Lean Canvas", :description => "A strategic management template to document activities and potential trade-offs - <a href='http://practicetrumpstheory.com/2012/02/why-lean-canvas/'>read more</a>.<br>Use this option when you are evaluating new business models, e.g., a start-up.", :lang => "en"
Template.create :templateid => "Thing", :name => "Thiel's One Thing", :description => "<a href='http://en.wikipedia.org/wiki/Peter_Thiel'>Peter Thiel</a> recommends to focus on just one thing at a time - <a href='http://blog.idonethis.com/post/37113345206/peter-thiels-unorthodox-management-philosophy-of'>read more</a>.<br>Use this option togehter with other templates to bring the most important thing you are working on today to mind.", :lang => "en"
Template.create :templateid => "SWOT", :name => "SWOT Analyse", :description => "Eine strukturierte Plannungsmethode um Stärken, Schwächen, Chancen und Risiken in einem Projekt zu analysieren - <a href='http://de.wikipedia.org/wiki/SWOT-Analyse'>mehr Infos</a>.<br>Diese Vorlage eignet sich als Start, wenn du Hyve.me das erste Mal verwendest.", :lang => "de"
Template.create :templateid => "Honeycomb", :name => "Honeycomb Vorlage", :description => "Eine Erweiterung des Projektmanagement-Dreiecks in Bezug auf validiertes Lernen - <a href='http://www.hyve.me/blog/?p=57'>mehr Infos (englisch)</a>.<br>Diese Vorlage ist für jede Art von Projekt anwendbar.", :lang => "de"
Template.create :templateid => "Porter", :name => "Branchenstrukturanalyse", :description => "Die Branchenstrukturanalyse dient der Strategieanalyse in der unternehmerischen Planung - <a href='http://de.wikipedia.org/wiki/Branchenstrukturanalyse'>mehr Infos</a>.<br>Diese Option eignet sich besonder für Projekte im Unternehmensumfeld.", :lang => "de"
Template.create :templateid => "Lean", :name => "Lean Canvas", :description => "Eine strategische Managementvorlage, um Aktivitäten und Entscheidungen abzuwägen - <a href='http://practicetrumpstheory.com/2012/02/why-lean-canvas/'>mehr Infos (englisch)</a>.<br>Diese Option eignet sich besoners für Geschäftsideen und junge Unternehmen.", :lang => "de"
Template.create :templateid => "Thing", :name => "Thiel's eine Sache", :description => "<a href='http://de.wikipedia.org/wiki/Peter_Thiel'>Peter Thiel</a> empfiehlt sich immer nur auf eine Sache zu fokusieren - <a href='http://blog.idonethis.com/post/37113345206/peter-thiels-unorthodox-management-philosophy-of'>mehr Infos (englisch)</a>.<br>Diese Option kann in Kombination mit anderen Vorlagen verwendet werden und hilft sich täglich seine Prioritäten zu vergegenwärtigen.", :lang => "de"
TemplateGroup.destroy_all
TemplateGroup.create :templateid => "SWOT", :templatename => "SWOT Analysis", :groupname => "Strengths", :lang => "en"
TemplateGroup.create :templateid => "SWOT", :templatename => "SWOT Analysis", :groupname => "Weaknesses", :lang => "en"
TemplateGroup.create :templateid => "SWOT", :templatename => "SWOT Analysis", :groupname => "Opportunities", :lang => "en"
TemplateGroup.create :templateid => "SWOT", :templatename => "SWOT Analysis", :groupname => "Threats", :lang => "en"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Template", :groupname => "Scope", :lang => "en"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Template", :groupname => "Resources", :lang => "en"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Template", :groupname => "Time", :lang => "en"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Template", :groupname => "Indicators", :lang => "en"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Template", :groupname => "Experiments", :lang => "en"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Template", :groupname => "Assumptions", :lang => "en"
TemplateGroup.create :templateid => "Porter", :templatename => "Porter's 5 Forces", :groupname => "Threat of new entrants", :lang => "en"
TemplateGroup.create :templateid => "Porter", :templatename => "Porter's 5 Forces", :groupname => "Threat of substitutes", :lang => "en"
TemplateGroup.create :templateid => "Porter", :templatename => "Porter's 5 Forces", :groupname => "Customer bargaining power", :lang => "en"
TemplateGroup.create :templateid => "Porter", :templatename => "Porter's 5 Forces", :groupname => "Supplier bargaining power", :lang => "en"
TemplateGroup.create :templateid => "Porter", :templatename => "Porter's 5 Forces", :groupname => "In-market rivalry", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Problem", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Customer segments", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Unique value proposition", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Solution", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Channels", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Revenue stream", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Cost structure", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Key metrics", :lang => "en"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Unfair advantage", :lang => "en"
TemplateGroup.create :templateid => "Thing", :templatename => "Thiel's One Thing", :groupname => "Today's thing", :lang => "en"
TemplateGroup.create :templateid => "SWOT", :templatename => "SWOT Analyse", :groupname => "Stärken", :lang => "de"
TemplateGroup.create :templateid => "SWOT", :templatename => "SWOT Analyse", :groupname => "Schwächen", :lang => "de"
TemplateGroup.create :templateid => "SWOT", :templatename => "SWOT Analyse", :groupname => "Chancen", :lang => "de"
TemplateGroup.create :templateid => "SWOT", :templatename => "SWOT Analyse", :groupname => "Risiken", :lang => "de"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Vorlage", :groupname => "Inhalt", :lang => "de"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Vorlage", :groupname => "Ressourcen", :lang => "de"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Vorlage", :groupname => "Zeit", :lang => "de"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Vorlage", :groupname => "Meßgrößen", :lang => "de"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Vorlage", :groupname => "Experimente", :lang => "de"
TemplateGroup.create :templateid => "Honeycomb", :templatename => "Honeycomb Vorlage", :groupname => "Annahmen", :lang => "de"
TemplateGroup.create :templateid => "Porter", :templatename => "Branchenstrukturanalyse", :groupname => "Bedrohung durch neue Anbieter", :lang => "de"
TemplateGroup.create :templateid => "Porter", :templatename => "Branchenstrukturanalyse", :groupname => "Bedrohung durch Ersatzprodukte", :lang => "de"
TemplateGroup.create :templateid => "Porter", :templatename => "Branchenstrukturanalyse", :groupname => "Verhandlungsstärke der Lieferanten", :lang => "de"
TemplateGroup.create :templateid => "Porter", :templatename => "Branchenstrukturanalyse", :groupname => "Verhandlungsstärke der Abnehmer", :lang => "de"
TemplateGroup.create :templateid => "Porter", :templatename => "Branchenstrukturanalyse", :groupname => "Rivalität unter den bestehenden Wettbewerbern", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Problem", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Kundengruppen", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Einzigartiges Werteversprechen", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Lösung", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Kanäle", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Umsatzströme", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Kostenstruktur", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Schlüsselmessgrößen", :lang => "de"
TemplateGroup.create :templateid => "Lean", :templatename => "Lean Canvas", :groupname => "Unfairer Vorteil", :lang => "de"
TemplateGroup.create :templateid => "Thing", :templatename => "Thiel's eine Sache", :groupname => "Heutiger Fokus", :lang => "de"
GroupItem.destroy_all
GroupItem.create :groupname => "Strengths", :itemname => "List of internal strengths", :itemtype => 3, :lang => "en", :description => "List all (internal) strengths for your project."
GroupItem.create :groupname => "Strengths", :itemname => "Strength on oppotunities and threats", :itemtype => 2, :lang => "en", :description => "Describe how to use strengths for opportunities and on threats."
GroupItem.create :groupname => "Strengths", :itemname => "Scale strength utilization", :itemtype => 1, :lang => "en", :description => "To what extend did you use the listed strengths since last reporting? Rate on a scale from 1 (not used at all) to 10 (maximum usage)."
GroupItem.create :groupname => "Weaknesses", :itemname => "List of internal weaknesses", :itemtype => 3, :lang => "en", :description => "List all (internal) weaknesses for your project."
GroupItem.create :groupname => "Weaknesses", :itemname => "Weaknesses on opportunities and threats", :itemtype => 2, :lang => "en", :description => "Describe consequences of weaknesses on opportunities and threats."
GroupItem.create :groupname => "Weaknesses", :itemname => "Scale effected weaknesses", :itemtype => 1, :lang => "en", :description => "To what extend effected listed weaknesses the project in a negative way since last reporting? Rate on a scale from 1 (no effect) to 10 (maximum possible effect)."
GroupItem.create :groupname => "Opportunities", :itemname => "List of external opportunities", :itemtype => 3, :lang => "en", :description => "List all (external) opportunites for your project."
GroupItem.create :groupname => "Opportunities", :itemname => "Maximizing strenghts and minimizing weaknesses", :itemtype => 2, :lang => "en", :description => "Describe how you can use listed opportunities to maximize the projects strengths and minimize the projects weaknesses."
GroupItem.create :groupname => "Opportunities", :itemname => "Scale embraced opportunities", :itemtype => 1, :lang => "en", :description => "To what extend where listed opportunities embraced since last reporting? Rate on a scale from 1 (none) to 10 (maximum usage)."
GroupItem.create :groupname => "Threats", :itemname => "List of external threats", :itemtype => 3, :lang => "en", :description => "List all (external) threads to your project."
GroupItem.create :groupname => "Threats", :itemname => "Effects on strengths and weaknesses", :itemtype => 2, :lang => "en", :description => "Describe the effects of listed threats on the projects strengths and weaknesses."
GroupItem.create :groupname => "Threats", :itemname => "Scale occurred threats", :itemtype => 1, :lang => "en", :description => "To what extend occurred listed threats since last reporting? Rate on a scale from 1 (none) to 10 (worst case)."
GroupItem.create :groupname => "Scope", :itemname => "List of goals", :itemtype => 3, :lang => "en", :description => "List all your project goals."
GroupItem.create :groupname => "Scope", :itemname => "Time spent on goals", :itemtype => 0, :lang => "en", :description => "How much time in hours was spent on reaching the listed goal since last reporting?"
GroupItem.create :groupname => "Scope", :itemname => "Scale goal reaching confidence", :itemtype => 1, :lang => "en", :description => "How confident are you to reach listed goals? Rate on a scale from 1 (no confidence) to 10 (absolutely sure)."
GroupItem.create :groupname => "Resources", :itemname => "List of resources", :itemtype => 3, :lang => "en", :description => "List all your projct resources."
GroupItem.create :groupname => "Resources", :itemname => "Scale workload on project members", :itemtype => 1, :lang => "en", :description => "To what extend is the current workload above or below average? Rate on a scale from 1 (almost no work) to 10 (burried below endless tasks)."
GroupItem.create :groupname => "Resources", :itemname => "Scale resource scope fit", :itemtype => 1, :lang => "en", :description => "Has the project the right resources? Rate on a scale from 1 (wrong and unusable resources) to 10 (perfect match)."
GroupItem.create :groupname => "Time", :itemname => "List of events and milestones", :itemtype => 3, :lang => "en", :description => "List all your upcoming project events and milestones."
GroupItem.create :groupname => "Time", :itemname => "Most critical upcoming event", :itemtype => 2, :lang => "en", :description => "What is your most critical upcoming event?"
GroupItem.create :groupname => "Time", :itemname => "Scale probability to comply with milestone plan", :itemtype => 1, :lang => "en", :description => "How confident are you about adhering to the milestone plan? Rate on a scale from 1 (milestone plan is unrealistic) to 10 (every milestone until project end will be met)"
GroupItem.create :groupname => "Indicators", :itemname => "List of performance indicators", :itemtype => 3, :lang => "en", :description => "List all your project auditing parameters."
GroupItem.create :groupname => "Indicators", :itemname => "How many indicators checked", :itemtype => 0, :lang => "en", :description => "How many of liste parameters did you check since last reporting?"
GroupItem.create :groupname => "Indicators", :itemname => "Oldest unverified indicator", :itemtype => 2, :lang => "en", :description => "What parameter was not checked for the longest time?"
GroupItem.create :groupname => "Indicators", :itemname => "What indicator changed most", :itemtype => 2, :lang => "en", :description => "What parameter changed most since last reporting?"
GroupItem.create :groupname => "Experiments", :itemname => "List of expected learnings", :itemtype => 3, :lang => "en", :description => "List all your planned experiments in the project."
GroupItem.create :groupname => "Experiments", :itemname => "Most important experiment to perform", :itemtype => 2, :lang => "en", :description => "What experiment is most important to finish next?"
GroupItem.create :groupname => "Experiments", :itemname => "Current learnings", :itemtype => 2, :lang => "en", :description => "What did you learn in the project since last reporting?"
GroupItem.create :groupname => "Assumptions", :itemname => "List of assumptions", :itemtype => 3, :lang => "en", :description => "List all your project assumptions."
GroupItem.create :groupname => "Assumptions", :itemname => "Most beneficiary assumption", :itemtype => 2, :lang => "en", :description => "What assumption benefited the project most since last reporting?"
GroupItem.create :groupname => "Assumptions", :itemname => "Most restrictive assumption", :itemtype => 2, :lang => "en", :description => "What assumption restricted the project most since last reporting?"
GroupItem.create :groupname => "Threat of new entrants", :itemname => "List threats for new entrants", :itemtype => 3, :lang => "en", :description => "List all threats for new entrants to the market of your offering."
GroupItem.create :groupname => "Threat of new entrants", :itemname => "Sunk costs for new entrants", :itemtype => 2, :lang => "en", :description => "Describe costs for new entrants that cannot be recovered later."
GroupItem.create :groupname => "Threat of new entrants", :itemname => "Scale how easy it is for new entrants", :itemtype => 1, :lang => "en", :description => "How easy is it for new entrants to enter your offerings market? Scale from 1 (very easy) to 10 (very hard)."
GroupItem.create :groupname => "Threat of new entrants", :itemname => "Scale your competitive advantage", :itemtype => 1, :lang => "en", :description => "To what extend do you have a competitive advantage (e.g., patents, distribution channels, economies of scale)? Rate on a scale from 1 (no competitive advantage) to 10 (many competitive advantages)."
GroupItem.create :groupname => "Threat of substitutes", :itemname => "List threats of substitute products or services", :itemtype => 3, :lang => "en", :description => "List all threats of substitute products or services in your offerings market."
GroupItem.create :groupname => "Threat of substitutes", :itemname => "Estimate switching costs", :itemtype => 0, :lang => "en", :description => "Estimate the cost of your customers for switching to another product or service."
GroupItem.create :groupname => "Threat of substitutes", :itemname => "Scale cross price elasticity", :itemtype => 1, :lang => "en", :description => "To what extent will a change in your offerings price trigger a shift in demand for a substitute? Rate from 1 (inelastic = no effect) to 10 (completly elastic = maxium effect)."
GroupItem.create :groupname => "Customer bargaining power", :itemname => "List bargaining powers of customers", :itemtype => 3, :lang => "en", :description => "List all bargaining powers of customers."
GroupItem.create :groupname => "Customer bargaining power", :itemname => "Scale buyer concentration", :itemtype => 1, :lang => "en", :description => "Rate the concentration of your buyers from 1 (low concentration and interaction) to 10 (high concentration and interaction)."
GroupItem.create :groupname => "Customer bargaining power", :itemname => "Scale possibility to segment buyers", :itemtype => 1, :lang => "en", :description => "To what extent is it possible to segment your buyers? Rate on a scale from 1 (no segmentation, single class of customers) to 10 (fine grained segmentation to tailor every aspect)."
GroupItem.create :groupname => "Supplier bargaining power", :itemname => "List bargaining powers of suppliers", :itemtype => 3, :lang => "en", :description => "List all bargaining powers of suppliers."
GroupItem.create :groupname => "Supplier bargaining power", :itemname => "Describe alternatives for sellers", :itemtype => 2, :lang => "en", :description => "Describe alternatives for your suppliers, e.g., forward integration, vendor lock-in, your market power."
GroupItem.create :groupname => "Supplier bargaining power", :itemname => "Scale seller concentration", :itemtype => 1, :lang => "en", :description => "Rate the concentration of sellers from 1 (low) to 10 (high)."
GroupItem.create :groupname => "In-market rivalry", :itemname => "List factors of competitive rivalry", :itemtype => 3, :lang => "en", :description => "List all factors of competitive rivalry in your offerings market."
GroupItem.create :groupname => "In-market rivalry", :itemname => "Estimate number of competitors", :itemtype => 0, :lang => "en", :description => "How many competitors are in your offerings market?"
GroupItem.create :groupname => "In-market rivalry", :itemname => "Scale extent of in-market fights", :itemtype => 1, :lang => "en", :description => "How intense is competition? Rate on a scale from 1 (respectful competition) to 10 (ruthless price wars)."
GroupItem.create :groupname => "In-market rivalry", :itemname => "Scale feasibility of coordination with rivals", :itemtype => 1, :lang => "en", :description => "To what extent is it feasible to coordinate with your rivals? Rate on a scale from 1 (no coordination) to 10 (full cooperation)."
GroupItem.create :groupname => "Problem", :itemname => "Describe problem", :itemtype => 2, :lang => "en", :description => "Describe the problem you want to solve."
GroupItem.create :groupname => "Problem", :itemname => "Number of problem discussions", :itemtype => 0, :lang => "en", :description => "With how many people have you discussed the problem since last reporting?"
GroupItem.create :groupname => "Customer segments", :itemname => "List customer segments", :itemtype => 3, :lang => "en", :description => "List all identified customer segments for your offering."
GroupItem.create :groupname => "Customer segments", :itemname => "Number of active customer segments", :itemtype => 0, :lang => "en", :description => "How many customer segments generated revenue since last reporting?"
GroupItem.create :groupname => "Unique value proposition", :itemname => "Describe unique value proposition", :itemtype => 2, :lang => "en", :description => "Describe the unique value proposition of your offering."
GroupItem.create :groupname => "Unique value proposition", :itemname => "Scale imitation potential for unique value proposition", :itemtype => 1, :lang => "en", :description => "To what extend can the value proposition of your offering be imitated by your competitors? Rate on a scale from 1 (very easy) to 10 (very hard)."
GroupItem.create :groupname => "Solution", :itemname => "Describe solution", :itemtype => 2, :lang => "en", :description => "Describe the planned solution for the problem you want to solve."
GroupItem.create :groupname => "Solution", :itemname => "Solution pivot", :itemtype => 8, :lang => "en", :description => "Did you pivot since last reporting?"
GroupItem.create :groupname => "Channels", :itemname => "List distribution channels", :itemtype => 3, :lang => "en", :description => "List all your offering's distribution channels."
GroupItem.create :groupname => "Channels", :itemname => "Number of active distribution channels", :itemtype => 0, :lang => "en", :description => "How many distribution channels generated revenue since last reporting?"
GroupItem.create :groupname => "Revenue stream", :itemname => "List of revenue streams", :itemtype => 3, :lang => "en", :description => "List all active and planned revenue streams from your offering."
GroupItem.create :groupname => "Revenue stream", :itemname => "Most profitable revenue stream", :itemtype => 2, :lang => "en", :description => "What is currently your most profitable revenue stream?"
GroupItem.create :groupname => "Cost structure", :itemname => "List cost structure items", :itemtype => 3, :lang => "en", :description => "List all one-time and periodical cost items."
GroupItem.create :groupname => "Cost structure", :itemname => "Spendings", :itemtype => 0, :lang => "en", :description => "How much did you spend since last reporting?"
GroupItem.create :groupname => "Key metrics", :itemname => "List key metrics", :itemtype => 3, :lang => "en", :description => "List all your project auditing key metrics."
GroupItem.create :groupname => "Key metrics", :itemname => "How many metrics checked", :itemtype => 0, :lang => "en", :description => "How many of liste parameters did you check since last reporting?"
GroupItem.create :groupname => "Key metrics", :itemname => "Oldest unverified indicator", :itemtype => 2, :lang => "en", :description => "What parameter was not checked for the longest time?"
GroupItem.create :groupname => "Key metrics", :itemname => "What indicator changed most", :itemtype => 2, :lang => "en", :description => "What parameter changed most since last reporting?"
GroupItem.create :groupname => "Unfair advantage", :itemname => "Describe unfair advantage", :itemtype => 2, :lang => "en", :description => "Describe the unfair advantage(s) you have over your competition."
GroupItem.create :groupname => "Unfair advantage", :itemname => "Duration of unfair advantage", :itemtype => 0, :lang => "en", :description => "Estimate how many month you can maintain your unfair advantage."
GroupItem.create :groupname => "Today's thing", :itemname => "Name your tracking item", :itemtype => 7, :lang => "en", :description => "What did you do today?"
GroupItem.create :groupname => "Stärken", :itemname => "Liste interner Stärken", :itemtype => 3, :lang => "de", :description => "Liste aller (internen) Stärken des Projekts."
GroupItem.create :groupname => "Stärken", :itemname => "Verwendung von Stärken bei Chancen und Risiken", :itemtype => 2, :lang => "de", :description => "Describe how to use strengths for opportunities and on threats."
GroupItem.create :groupname => "Stärken", :itemname => "Skaliere die Anwendung der Stärken", :itemtype => 1, :lang => "de", :description => "To what extend did you use the listed strengths since last reporting? Rate on a scale from 1 (not used at all) to 10 (maximum usage)."
GroupItem.create :groupname => "Schwächen", :itemname => "List of internal weaknesses", :itemtype => 3, :lang => "de", :description => "List all (internal) weaknesses for your project."
GroupItem.create :groupname => "Schwächen", :itemname => "Weaknesses on opportunities and threats", :itemtype => 2, :lang => "de", :description => "Describe consequences of weaknesses on opportunities and threats."
GroupItem.create :groupname => "Schwächen", :itemname => "Scale effected weaknesses", :itemtype => 1, :lang => "de", :description => "To what extend effected listed weaknesses the project in a negative way since last reporting? Rate on a scale from 1 (no effect) to 10 (maximum possible effect)."
GroupItem.create :groupname => "Chancen", :itemname => "List of external opportunities", :itemtype => 3, :lang => "de", :description => "List all (external) opportunites for your project."
GroupItem.create :groupname => "Chancen", :itemname => "Maximizing strenghts and minimizing weaknesses", :itemtype => 2, :lang => "de", :description => "Describe how you can use listed opportunities to maximize the projects strengths and minimize the projects weaknesses."
GroupItem.create :groupname => "Chancen", :itemname => "Scale embraced opportunities", :itemtype => 1, :lang => "de", :description => "To what extend where listed opportunities embraced since last reporting? Rate on a scale from 1 (none) to 10 (maximum usage)."
GroupItem.create :groupname => "Risiken", :itemname => "List of external threats", :itemtype => 3, :lang => "de", :description => "List all (external) threads to your project."
GroupItem.create :groupname => "Risiken", :itemname => "Effects on strengths and weaknesses", :itemtype => 2, :lang => "de", :description => "Describe the effects of listed threats on the projects strengths and weaknesses."
GroupItem.create :groupname => "Risiken", :itemname => "Scale occurred threats", :itemtype => 1, :lang => "de", :description => "To what extend occurred listed threats since last reporting? Rate on a scale from 1 (none) to 10 (worst case)."
GroupItem.create :groupname => "Inhalt", :itemname => "List of goals", :itemtype => 3, :lang => "de", :description => "List all your project goals."
GroupItem.create :groupname => "Inhalt", :itemname => "Time spent on goals", :itemtype => 0, :lang => "de", :description => "How much time in hours was spent on reaching the listed goal since last reporting?"
GroupItem.create :groupname => "Inhalt", :itemname => "Scale goal reaching confidence", :itemtype => 1, :lang => "de", :description => "How confident are you to reach listed goals? Rate on a scale from 1 (no confidence) to 10 (absolutely sure)."
GroupItem.create :groupname => "Ressourcen", :itemname => "List of resources", :itemtype => 3, :lang => "de", :description => "List all your projct resources."
GroupItem.create :groupname => "Ressourcen", :itemname => "Scale workload on project members", :itemtype => 1, :lang => "de", :description => "To what extend is the current workload above or below average? Rate on a scale from 1 (almost no work) to 10 (burried below endless tasks)."
GroupItem.create :groupname => "Ressourcen", :itemname => "Scale resource scope fit", :itemtype => 1, :lang => "de", :description => "Has the project the right resources? Rate on a scale from 1 (wrong and unusable resources) to 10 (perfect match)."
GroupItem.create :groupname => "Zeit", :itemname => "List of events and milestones", :itemtype => 3, :lang => "de", :description => "List all your upcoming project events and milestones."
GroupItem.create :groupname => "Zeit", :itemname => "Most critical upcoming event", :itemtype => 2, :lang => "de", :description => "What is your most critical upcoming event?"
GroupItem.create :groupname => "Zeit", :itemname => "Scale probability to comply with milestone plan", :itemtype => 1, :lang => "de", :description => "How confident are you about adhering to the milestone plan? Rate on a scale from 1 (milestone plan is unrealistic) to 10 (every milestone until project end will be met)"
GroupItem.create :groupname => "Meßgrößen", :itemname => "List of performance indicators", :itemtype => 3, :lang => "de", :description => "List all your project auditing parameters."
GroupItem.create :groupname => "Meßgrößen", :itemname => "How many indicators checked", :itemtype => 0, :lang => "de", :description => "How many of liste parameters did you check since last reporting?"
GroupItem.create :groupname => "Meßgrößen", :itemname => "Oldest unverified indicator", :itemtype => 2, :lang => "de", :description => "What parameter was not checked for the longest time?"
GroupItem.create :groupname => "Meßgrößen", :itemname => "What indicator changed most", :itemtype => 2, :lang => "de", :description => "What parameter changed most since last reporting?"
GroupItem.create :groupname => "Experimente", :itemname => "List of expected learnings", :itemtype => 3, :lang => "de", :description => "List all your planned experiments in the project."
GroupItem.create :groupname => "Experimente", :itemname => "Most important experiment to perform", :itemtype => 2, :lang => "de", :description => "What experiment is most important to finish next?"
GroupItem.create :groupname => "Experimente", :itemname => "Current learnings", :itemtype => 2, :lang => "de", :description => "What did you learn in the project since last reporting?"
GroupItem.create :groupname => "Annahmen", :itemname => "List of assumptions", :itemtype => 3, :lang => "de", :description => "List all your project assumptions."
GroupItem.create :groupname => "Annahmen", :itemname => "Most beneficiary assumption", :itemtype => 2, :lang => "de", :description => "What assumption benefited the project most since last reporting?"
GroupItem.create :groupname => "Annahmen", :itemname => "Most restrictive assumption", :itemtype => 2, :lang => "de", :description => "What assumption restricted the project most since last reporting?"
GroupItem.create :groupname => "Bedrohung durch neue Anbieter", :itemname => "List threats for new entrants", :itemtype => 3, :lang => "de", :description => "List all threats for new entrants to the market of your offering."
GroupItem.create :groupname => "Bedrohung durch neue Anbieter", :itemname => "Sunk costs for new entrants", :itemtype => 2, :lang => "de", :description => "Describe costs for new entrants that cannot be recovered later."
GroupItem.create :groupname => "Bedrohung durch neue Anbieter", :itemname => "Scale how easy it is for new entrants", :itemtype => 1, :lang => "de", :description => "How easy is it for new entrants to enter your offerings market? Scale from 1 (very easy) to 10 (very hard)."
GroupItem.create :groupname => "Bedrohung durch neue Anbieter", :itemname => "Scale your competitive advantage", :itemtype => 1, :lang => "de", :description => "To what extend do you have a competitive advantage (e.g., patents, distribution channels, economies of scale)? Rate on a scale from 1 (no competitive advantage) to 10 (many competitive advantages)."
GroupItem.create :groupname => "Bedrohung durch Ersatzprodukte", :itemname => "List threats of substitute products or services", :itemtype => 3, :lang => "de", :description => "List all threats of substitute products or services in your offerings market."
GroupItem.create :groupname => "Bedrohung durch Ersatzprodukte", :itemname => "Estimate switching costs", :itemtype => 0, :lang => "de", :description => "Estimate the cost of your customers for switching to another product or service."
GroupItem.create :groupname => "Bedrohung durch Ersatzprodukte", :itemname => "Scale cross price elasticity", :itemtype => 1, :lang => "de", :description => "To what extent will a change in your offerings price trigger a shift in demand for a substitute? Rate from 1 (inelastic = no effect) to 10 (completly elastic = maxium effect)."
GroupItem.create :groupname => "Verhandlungsstärke der Lieferanten", :itemname => "List bargaining powers of customers", :itemtype => 3, :lang => "de", :description => "List all bargaining powers of customers."
GroupItem.create :groupname => "Verhandlungsstärke der Lieferanten", :itemname => "Scale buyer concentration", :itemtype => 1, :lang => "de", :description => "Rate the concentration of your buyers from 1 (low concentration and interaction) to 10 (high concentration and interaction)."
GroupItem.create :groupname => "Verhandlungsstärke der Lieferanten", :itemname => "Scale possibility to segment buyers", :itemtype => 1, :lang => "de", :description => "To what extent is it possible to segment your buyers? Rate on a scale from 1 (no segmentation, single class of customers) to 10 (fine grained segmentation to tailor every aspect)."
GroupItem.create :groupname => "Verhandlungsstärke der Abnehmer", :itemname => "List bargaining powers of suppliers", :itemtype => 3, :lang => "de", :description => "List all bargaining powers of suppliers."
GroupItem.create :groupname => "Verhandlungsstärke der Abnehmer", :itemname => "Describe alternatives for sellers", :itemtype => 2, :lang => "de", :description => "Describe alternatives for your suppliers, e.g., forward integration, vendor lock-in, your market power."
GroupItem.create :groupname => "Verhandlungsstärke der Abnehmer", :itemname => "Scale seller concentration", :itemtype => 1, :lang => "de", :description => "Rate the concentration of sellers from 1 (low) to 10 (high)."
GroupItem.create :groupname => "Rivalität unter den bestehenden Wettbewerbern", :itemname => "List factors of competitive rivalry", :itemtype => 3, :lang => "de", :description => "List all factors of competitive rivalry in your offerings market."
GroupItem.create :groupname => "Rivalität unter den bestehenden Wettbewerbern", :itemname => "Estimate number of competitors", :itemtype => 0, :lang => "de", :description => "How many competitors are in your offerings market?"
GroupItem.create :groupname => "Rivalität unter den bestehenden Wettbewerbern", :itemname => "Scale extent of in-market fights", :itemtype => 1, :lang => "de", :description => "How intense is competition? Rate on a scale from 1 (respectful competition) to 10 (ruthless price wars)."
GroupItem.create :groupname => "Rivalität unter den bestehenden Wettbewerbern", :itemname => "Scale feasibility of coordination with rivals", :itemtype => 1, :lang => "de", :description => "To what extent is it feasible to coordinate with your rivals? Rate on a scale from 1 (no coordination) to 10 (full cooperation)."
GroupItem.create :groupname => "Problem", :itemname => "Describe problem", :itemtype => 2, :lang => "de", :description => "Describe the problem you want to solve."
GroupItem.create :groupname => "Problem", :itemname => "Number of problem discussions", :itemtype => 0, :lang => "de", :description => "With how many people have you discussed the problem since last reporting?"
GroupItem.create :groupname => "Kundengruppen", :itemname => "List customer segments", :itemtype => 3, :lang => "de", :description => "List all identified customer segments for your offering."
GroupItem.create :groupname => "Kundengruppen", :itemname => "Number of active customer segments", :itemtype => 0, :lang => "de", :description => "How many customer segments generated revenue since last reporting?"
GroupItem.create :groupname => "Einzigartiges Werteversprechen", :itemname => "Describe unique value proposition", :itemtype => 2, :lang => "de", :description => "Describe the unique value proposition of your offering."
GroupItem.create :groupname => "Einzigartiges Werteversprechen", :itemname => "Scale imitation potential for unique value proposition", :itemtype => 1, :lang => "de", :description => "To what extend can the value proposition of your offering be imitated by your competitors? Rate on a scale from 1 (very easy) to 10 (very hard)."
GroupItem.create :groupname => "Lösung", :itemname => "Describe solution", :itemtype => 2, :lang => "de", :description => "Describe the planned solution for the problem you want to solve."
GroupItem.create :groupname => "Lösung", :itemname => "Solution pivot", :itemtype => 8, :lang => "de", :description => "Did you pivot since last reporting?"
GroupItem.create :groupname => "Kanäle", :itemname => "List distribution channels", :itemtype => 3, :lang => "de", :description => "List all your offering's distribution channels."
GroupItem.create :groupname => "Kanäle", :itemname => "Number of active distribution channels", :itemtype => 0, :lang => "de", :description => "How many distribution channels generated revenue since last reporting?"
GroupItem.create :groupname => "Umsatzströme", :itemname => "List of revenue streams", :itemtype => 3, :lang => "de", :description => "List all active and planned revenue streams from your offering."
GroupItem.create :groupname => "Umsatzströme", :itemname => "Most profitable revenue stream", :itemtype => 2, :lang => "de", :description => "What is currently your most profitable revenue stream?"
GroupItem.create :groupname => "Kostenstruktur", :itemname => "List cost structure items", :itemtype => 3, :lang => "de", :description => "List all one-time and periodical cost items."
GroupItem.create :groupname => "Kostenstruktur", :itemname => "Spendings", :itemtype => 0, :lang => "de", :description => "How much did you spend since last reporting?"
GroupItem.create :groupname => "Schlüsselmessgrößen", :itemname => "List key metrics", :itemtype => 3, :lang => "de", :description => "List all your project auditing key metrics."
GroupItem.create :groupname => "Schlüsselmessgrößen", :itemname => "How many metrics checked", :itemtype => 0, :lang => "de", :description => "How many of liste parameters did you check since last reporting?"
GroupItem.create :groupname => "Schlüsselmessgrößen", :itemname => "Oldest unverified indicator", :itemtype => 2, :lang => "de", :description => "What parameter was not checked for the longest time?"
GroupItem.create :groupname => "Schlüsselmessgrößen", :itemname => "What indicator changed most", :itemtype => 2, :lang => "de", :description => "What parameter changed most since last reporting?"
GroupItem.create :groupname => "Unfairer Vorteil", :itemname => "Describe unfair advantage", :itemtype => 2, :lang => "de", :description => "Describe the unfair advantage(s) you have over your competition."
GroupItem.create :groupname => "Unfairer Vorteil", :itemname => "Duration of unfair advantage", :itemtype => 0, :lang => "de", :description => "Estimate how many month you can maintain your unfair advantage."
GroupItem.create :groupname => "Heutiger Fokus", :itemname => "Benenne deine Sache", :itemtype => 7, :lang => "de", :description => "Was machst du heute?"
